#!/usr/bin/env python3
import argparse
from pathlib import Path


def parse_scalar(value):
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [item.strip() for item in inner.split(",")]
    return value


def parse_manifest(path):
    root = {}
    functions = []
    current = None
    in_functions = False

    for raw_line in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        stripped = line.strip()

        if stripped == "functions:":
            in_functions = True
            continue

        if not in_functions:
            key, value = stripped.split(":", 1)
            root[key.strip()] = parse_scalar(value)
            continue

        if stripped.startswith("- "):
            if current:
                functions.append(current)
            current = {}
            item = stripped[2:]
            if item:
                key, value = item.split(":", 1)
                current[key.strip()] = parse_scalar(value)
            continue

        if current is None:
            raise ValueError(f"manifest field outside function item: {raw_line}")
        key, value = stripped.split(":", 1)
        current[key.strip()] = parse_scalar(value)

    if current:
        functions.append(current)

    root["functions"] = functions
    return root


def prop_quote(value):
    return '"' + value.replace('"', '\\"') + '"'


def render_create(function, jar_url, replace):
    name = function["name"]
    args = ", ".join(function.get("args", []))
    returns = function["returns"]
    symbol = function["symbol"]
    isolation = function.get("isolation", "shared")
    create = "CREATE OR REPLACE FUNCTION" if replace else "CREATE FUNCTION IF NOT EXISTS"
    return (
        f"{create} {name}({args})\n"
        f"RETURNS {returns}\n"
        "PROPERTIES (\n"
        f"  \"symbol\" = {prop_quote(symbol)},\n"
        "  \"type\" = \"StarrocksJar\",\n"
        f"  \"file\" = {prop_quote(jar_url)},\n"
        f"  \"isolation\" = {prop_quote(isolation)}\n"
        ");"
    )


def render_drop(function):
    args = ", ".join(function.get("args", []))
    return f"DROP FUNCTION IF EXISTS {function['name']}({args});"


def db_name(function_name):
    if "." not in function_name:
        return None
    return function_name.split(".", 1)[0]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", default="src/main/resources/function-metadata.yaml")
    parser.add_argument("--jar-url", required=True)
    parser.add_argument("--out-dir", default="generated")
    parser.add_argument("--no-replace", action="store_true")
    args = parser.parse_args()

    manifest = parse_manifest(args.manifest)
    functions = manifest["functions"]
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    databases = sorted({db_name(fn["name"]) for fn in functions if db_name(fn["name"])})
    create_lines = [
        "-- Generated by tools/generate_sql.py. Do not edit manually.",
        f"-- UDF jar: {args.jar_url}",
        "",
    ]
    for database in databases:
        create_lines.append(f"CREATE DATABASE IF NOT EXISTS {database};")
    if databases:
        create_lines.append("")
    create_lines.extend(render_create(fn, args.jar_url, not args.no_replace) for fn in functions)
    create_lines.append("")

    drop_lines = [
        "-- Generated by tools/generate_sql.py. Do not edit manually.",
        "",
    ]
    drop_lines.extend(render_drop(fn) for fn in reversed(functions))
    drop_lines.append("")

    (out_dir / "create-functions.sql").write_text("\n\n".join(create_lines), encoding="utf-8")
    (out_dir / "drop-functions.sql").write_text("\n\n".join(drop_lines), encoding="utf-8")


if __name__ == "__main__":
    main()
