# StarRocks all-in-one image for CentOS/UBI production (FE + BE).
# Based on docker/dockerfiles/allin1/allin1-ubi.Dockerfile with JDK 17 for FE 3.4+.
#
# Build:
#   ./deploy/build.sh --target allin1-ubi --artifact-source docker
#
ARG ARTIFACT_SOURCE=image
ARG WITH_DEBUG_INFO=false

ARG ARTIFACTIMAGE=starrocks/artifacts-centos7:latest
FROM ${ARTIFACTIMAGE} as artifacts-from-image

FROM busybox:latest as artifacts-from-local
ARG LOCAL_REPO_PATH

COPY ${LOCAL_REPO_PATH}/output/fe /release/fe_artifacts/fe
COPY ${LOCAL_REPO_PATH}/output/be /release/be_artifacts/be

FROM artifacts-from-${ARTIFACT_SOURCE} as artifacts
ARG WITH_DEBUG_INFO

RUN if [ "$WITH_DEBUG_INFO" = "false" ]; then rm -f /release/be_artifacts/be/lib/starrocks_be.debuginfo; fi

FROM registry.access.redhat.com/ubi8/ubi:8.7
ARG DEPLOYDIR=/data/deploy
ENV SR_HOME=${DEPLOYDIR}/starrocks

RUN yum install -y java-17-openjdk-devel tzdata openssl curl vim ca-certificates fontconfig gzip tar less hostname procps-ng lsof python3-pip nginx nc && \
    rpm -ivh https://repo.mysql.com/mysql80-community-release-el8-7.noarch.rpm && \
    yum -y install mysql-community-client --nogpgcheck && \
    yum remove -y mysql80-community-release && \
    pip3 install supervisor && \
    yum clean all
ENV JAVA_HOME=/usr/lib/jvm/java-17

WORKDIR $DEPLOYDIR

COPY --from=artifacts /release/be_artifacts/ $DEPLOYDIR/starrocks
COPY --from=artifacts /release/fe_artifacts/ $DEPLOYDIR/starrocks

COPY docker/dockerfiles/allin1/*.sh docker/dockerfiles/allin1/*.conf docker/dockerfiles/allin1/*.txt $DEPLOYDIR
COPY docker/dockerfiles/allin1/services/ $SR_HOME
RUN cat be.conf >> $DEPLOYDIR/starrocks/be/conf/be.conf && \
    cat fe.conf >> $DEPLOYDIR/starrocks/fe/conf/fe.conf && \
    rm -f be.conf fe.conf && \
    mkdir -p $DEPLOYDIR/starrocks/fe/meta $DEPLOYDIR/starrocks/be/storage && touch /.dockerenv

CMD ./entrypoint.sh
